Web/ENews.Web/Areas/Administration/Controllers/SubCategoriesController.cs
namespace ENews.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using ENews.Common;
    using ENews.Data;
    using ENews.Data.Models;
    using ENews.Services;
    using ENews.Services.Data;
    using ENews.Web.ViewModels.Administration.Categories;
    using ENews.Web.ViewModels.Administration.SubCategories;
    using ENews.Web.ViewModels.MembersArea.Articles;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class SubCategoriesController : Controller
    {
        private readonly ISubCategoriesService subCategoriesService;
        private readonly IPagingService pagingService;
        private readonly ICategoriesService categoriesService;

        public SubCategoriesController(
            ISubCategoriesService subCategoriesService,
            IPagingService pagingService,
            ICategoriesService categoriesService)
        {
            this.subCategoriesService = subCategoriesService;
            this.pagingService = pagingService;
            this.categoriesService = categoriesService;
        }

        public IActionResult Active(int page = 1)
        {
            var skip = this.pagingService.CountSkip(page, GlobalConstants.AdministrationItemsPerPage);

            var result = this.subCategoriesService.GetAllSubCategories<IndexSubCategoryViewModel>(GlobalConstants.AdministrationItemsPerPage, skip);

            var subCategoriesCount = this.subCategoriesService.GetCountOfActiveSubCategories();

            var model = new IndexSubCategoriesViewModel()
            {
                SubCategories = result,
                PagesCount = this.pagingService.PagesCount(subCategoriesCount, GlobalConstants.AdministrationItemsPerPage),
            };
            model.CurrentPage = this.pagingService.SetPage(page, model.PagesCount);

            return this.View(model);
        }

        public IActionResult Deleted(int page = 1)
        {
            var skip = this.pagingService.CountSkip(page, GlobalConstants.AdministrationItemsPerPage);

            var result = this.subCategoriesService.GetAllDeletedSubCategories<IndexSubCategoryViewModel>(GlobalConstants.AdministrationItemsPerPage, skip);

            var subCategoriesCount = this.subCategoriesService.GetCountOfDeletedSubCategories();

            var model = new IndexSubCategoriesViewModel()
            {
                SubCategories = result,
                PagesCount = this.pagingService.SetPage(subCategoriesCount, GlobalConstants.AdministrationItemsPerPage),
            };
            model.CurrentPage = this.pagingService.SetPage(page, model.PagesCount);

            return this.View(model);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var category = await this.subCategoriesService.GetSubCategoryById<IndexSubCategoryViewModel>((int)id);
            if (category == null)
            {
                return this.NotFound();
            }

            return this.View(category);
        }

        public IActionResult Create()
        {
            var categories = this.categoriesService.GetAllCategories<CategoriesDropDownViewModel>();
            var viewModel = new SubCategoryCreateInputModel()
            {
                CategoriesDropDown = categories,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubCategoryCreateInputModel inputModel)
        {
            inputModel.CategoriesDropDown = this.categoriesService.GetAllCategories<CategoriesDropDownViewModel>();
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            if (await this.subCategoriesService.SubCategoryExistsByName(inputModel.Title))
            {
                this.ModelState.AddModelError(inputModel.Title, $"Title - {inputModel.Title} already exists");
                return this.View(inputModel);
            }

            if (!await this.categoriesService.CategoryExistsById(inputModel.CategoryId))
            {
                this.ModelState.AddModelError("Category", "Select appropriate category!");
                return this.View(inputModel);
            }

            await this.subCategoriesService.CreateSubCategoryAsync(inputModel);
            return this.RedirectToAction(nameof(this.Active));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var subCategory = await this.subCategoriesService.GetSubCategoryModelById((int)id);

            if (subCategory == null)
            {
                return this.NotFound();
            }

            var categories = this.categoriesService.GetAllCategories<CategoriesDropDownViewModel>();
            this.ViewData["CategoryId"] = new SelectList(categories, "Id", "Title", subCategory.CategoryId);
            return this.View(subCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,CategoryId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] SubCategory subCategory)
        {
            if (id != subCategory.Id)
            {
                return this.NotFound();
            }

            var categories = this.categoriesService.GetAllCategories<DropDownCategories>();
            if (await this.subCategoriesService.SubCategoryExistsByName(subCategory.Title, subCategory.CategoryId))
            {
                this.ViewData["CategoryId"] = new SelectList(categories, "Id", "Title", subCategory.CategoryId);
                this.ModelState.AddModelError(subCategory.Title, $"Title - {subCategory.Title} already exists");
                return this.View(subCategory);
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    await this.subCategoriesService.Update(subCategory);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await this.subCategoriesService.SubCategoryExistsById(subCategory.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Active));
            }

            this.ViewData["CategoryId"] = new SelectList(categories, "Id", "Title", subCategory.CategoryId);
            return this.View(subCategory);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            await this.subCategoriesService.DeleteById((int)id);

            return this.RedirectToAction(nameof(this.Active));
        }

        public async Task<IActionResult> Undelete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            await this.subCategoriesService.UndeleteById((int)id);

            return this.RedirectToAction(nameof(this.Deleted));
        }

        public async Task<IActionResult> HardDelete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var subCategory = await this.subCategoriesService.GetSubCategoryById<IndexSubCategoryViewModel>((int)id);
            if (subCategory == null)
            {
                return this.NotFound();
            }

            return this.View(subCategory);
        }

        [HttpPost]
        [ActionName("HardDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.subCategoriesService.HardDeleteById(id);

            return this.RedirectToAction(nameof(this.Active));
        }
    }
}

Web/ENews.Web/Controllers/SubCategoriesController.cs
namespace ENews.Web.Controllers
{
    using ENews.Common;
    using ENews.Services;
    using ENews.Services.Data;
    using ENews.Web.ViewModels;
    using ENews.Web.ViewModels.Categories;
    using Microsoft.AspNetCore.Mvc;

    public class SubCategoriesController : Controller
    {
        private readonly ISubCategoriesService subCategoriesService;
        private readonly IArticlesService articleService;
        private readonly IPagingService pagingService;

        public SubCategoriesController(
            ISubCategoriesService subCategoriesService,
            IArticlesService articleService,
            IPagingService pagingService)
        {
            this.subCategoriesService = subCategoriesService;
            this.articleService = articleService;
            this.pagingService = pagingService;
        }

        public IActionResult Index(string data, int page = 1)
        {
            var viewModel = this.subCategoriesService.GetSubCategoryByName<SubCategoryArticlesViewModel>(data);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            var skip = this.pagingService.CountSkip(page, GlobalConstants.ArticlePerPage);
            viewModel.Route = GlobalConstants.SubCategoryRoute;
            viewModel.Data = data;
            viewModel.SubData = viewModel.CategoryTitle;

            viewModel.SubCategoryArticles = this.articleService.GetAllBySubCategoryId<ArticlePreviewViewModel>(viewModel.Id, GlobalConstants.ArticlePerPage, skip);

            var articlesCount = this.articleService.GetCountBySubCategoryId(viewModel.Id);

            viewModel.PagesCount = this.pagingService.PagesCount(articlesCount, GlobalConstants.ArticlePerPage);

            viewModel.CurrentPage = this.pagingService.SetPage(page, viewModel.PagesCount);

            return this.View(viewModel);
        }
    }
}

Web/ENews.Web/Areas/Administration/Views/SubCategories/Active.cshtml
@*@model IEnumerable<ENews.Data.Models.Category>*@
@model ENews.Web.ViewModels.Administration.SubCategories.IndexSubCategoriesViewModel

@{
    ViewData["Title"] = "Active subcategories";
}

<div class="alert alert-primary" role="alert">
    <div class="text-center">
        @ViewData["Title"] list
    </div>
</div>
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="">@ViewData["Title"]</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-area="Administration" asp-controller="SubCategories" asp-action="Deleted">Deleted subcategories</a>
            </li>
            <li class=" flex-grow-1"></li>
            <li class="nav-item">
                <a class="nav-link" asp-area="Administration" asp-controller="SubCategories" asp-action="Create">Create New</a>
            </li>
        </ul>
    </div>
    <table class="table table-responsive-lg">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().Title)
                </th>
                <th>
                    @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().CategoryTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().ModifiedOn)
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.SubCategories)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CategoryTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedOn)
                    </td>
                    <td>
                        <ul>
                            <li>
                                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            </li>
                            <li>
                                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                            </li>
                            <li>
                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<partial name="_Paging" />

Web/ENews.Web/Areas/Administration/Views/SubCategories/Create.cshtml
@model ENews.Web.ViewModels.Administration.SubCategories.SubCategoryCreateInputModel

@{
    ViewData["Title"] = "Create";
    var categories = Model.CategoriesDropDown.Select(c => new SelectListItem(c.Title, c.Id.ToString()));
}

<h1>Create</h1>

<h4>SubCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.CategoryId"></label>
                <select id="ddlcategory" asp-for="@Model.CategoryId" asp-items="categories" class="form-control"></select>
                <span asp-validation-for="@Model.CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Active">Back to active list</a>
</div>

Web/ENews.Web/Areas/Administration/Views/SubCategories/Deleted.cshtml
@*@model IEnumerable<ENews.Data.Models.Category>*@
@model ENews.Web.ViewModels.Administration.SubCategories.IndexSubCategoriesViewModel

@{
    ViewData["Title"] = "Deleted subcategories";
}

<div class="alert alert-danger" role="alert">
    <div class="text-center">
        @ViewData["Title"] list
    </div>
</div>
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs">
            <li class="nav-item active">
                <a class="nav-link" asp-area="Administration" asp-controller="SubCategories" asp-action="Active">Active subcategries</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="">@ViewData["Title"]</a>
            </li>
            <li class=" flex-grow-1"></li>
            <li class="nav-item">
                <a class="nav-link" asp-area="Administration" asp-controller="SubCategories" asp-action="Create">Create New</a>
            </li>
        </ul>
    </div>
    <table class="table table-responsive-lg">
        <thead class="thead-dark">
            <tr>
                <th>
                    @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().Title)
                </th>
                <th>
                    @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().CategoryTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().DeletedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().ModifiedOn)
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.SubCategories)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CategoryTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DeletedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedOn)
                    </td>
                    <td>
                        <ul>
                            <li>
                                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                            </li>
                            <li>
                                <a asp-action="Undelete" asp-route-id="@item.Id">Restore</a>
                            </li>
                            <li>
                                <a asp-action="HardDelete" asp-route-id="@item.Id">Hard Delete</a>
                            </li>
                        </ul>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<partial name="_Paging" />

Web/ENews.Web/Areas/Administration/Views/SubCategories/Details.cshtml
@model ENews.Web.ViewModels.Administration.SubCategories.IndexSubCategoryViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Subcategory</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CategoryTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DeletedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DeletedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    @if (this.Model.IsDeleted)
    {
        <a asp-action="Deleted">Back to list</a>
    }
    else
    {
        <a asp-action="Active">Back to list</a>
    }
</div>

Web/ENews.Web/Areas/Administration/Views/SubCategories/Edit.cshtml
@model ENews.Data.Models.SubCategory

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SubCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DeletedOn" class="control-label"></label>
                <input asp-for="DeletedOn" class="form-control" />
                <span asp-validation-for="DeletedOn" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" />
                <span asp-validation-for="CreatedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedOn" class="control-label"></label>
                <input asp-for="ModifiedOn" class="form-control" />
                <span asp-validation-for="ModifiedOn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Active">Back to List</a>
</div>

Web/ENews.Web/Areas/Administration/Views/SubCategories/HardDelete.cshtml
@model ENews.Web.ViewModels.Administration.SubCategories.IndexSubCategoryViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to permanently delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CategoryTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DeletedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DeletedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
    </dl>

    <form asp-action="HardDelete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Deleted">Back to List</a>
    </form>
</div>

Web/ENews.Web/Areas/Administration/Views/SubCategories/Index.cshtml
@*@model IEnumerable<ENews.Data.Models.Category>*@
@model ENews.Web.ViewModels.Administration.SubCategories.IndexSubCategoriesViewModel

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().Title)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().CategoryTitle)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().IsDeleted)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().DeletedOn)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.SubCategories.FirstOrDefault().ModifiedOn)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.SubCategories)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsDeleted)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeletedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifiedOn)
                </td>
                <td>
                    <ul>
                        <li>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                        </li>
                        <li>
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                        </li>
                        @if (!item.IsDeleted)
                        {
                            <li>
                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a asp-action="Undelete" asp-route-id="@item.Id">Restore</a>
                            </li>
                        }
                        <li>
                            <a asp-action="HardDelete" asp-route-id="@item.Id">Hard Delete</a>
                        </li>
                    </ul>
                </td>
            </tr>
        }
    </tbody>
</table>