Web/ENews.Web/Areas/Administration/Controllers/ArticlesController.cs
namespace ENews.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using ENews.Common;
    using ENews.Data.Models;
    using ENews.Services;
    using ENews.Services.Data;
    using ENews.Web.ViewModels.MembersArea.Home;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class ArticlesController : Controller
    {
        private readonly IArticlesService articleService;
        private readonly ICategoriesService categoriesService;
        private readonly ISubCategoriesService subCategoriesService;
        private readonly IPagingService pagingService;
        private readonly UserManager<ApplicationUser> userManager;

        public ArticlesController(
            IArticlesService articleService,
            ICategoriesService categoriesService,
            ISubCategoriesService subCategoriesService,
            IPagingService pagingService,
            UserManager<ApplicationUser> userManager)
        {
            this.articleService = articleService;
            this.categoriesService = categoriesService;
            this.subCategoriesService = subCategoriesService;
            this.pagingService = pagingService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> AllActive(int page = 1)
        {
            var skip = this.pagingService.CountSkip(page, GlobalConstants.AdministrationItemsPerPage);

            var user = await this.userManager.GetUserAsync(this.User);

            var result = this.articleService.GetAllActive<IndexArticleViewModel>(GlobalConstants.AdministrationItemsPerPage, skip);

            var articlesCount = this.articleService.GetCountByAuthorId(user.Id);

            var model = new IndexArticlesViewModel()
            {
                Articles = result,
                PagesCount = this.pagingService.PagesCount(articlesCount, GlobalConstants.AdministrationItemsPerPage),
            };

            model.CurrentPage = this.pagingService.SetPage(page, model.PagesCount);

            return this.View(model);
        }

        public async Task<IActionResult> AllDeleted(int page = 1)
        {
            var skip = this.pagingService.CountSkip(page, GlobalConstants.AdministrationItemsPerPage);

            var user = await this.userManager.GetUserAsync(this.User);

            var result = this.articleService.GetAllDeleted<IndexArticleViewModel>(GlobalConstants.AdministrationItemsPerPage, skip);

            var articlesCount = this.articleService.GetCountByAuthorIdDeleted(user.Id);

            var model = new IndexArticlesViewModel()
            {
                Articles = result,
                PagesCount = this.pagingService.PagesCount(articlesCount, GlobalConstants.AdministrationItemsPerPage),
            };
            model.CurrentPage = this.pagingService.SetPage(page, model.PagesCount);

            return this.View(model);
        }

        public async Task<IActionResult> HardDelete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var article = await this.articleService.GetArticleByIdWithDeleted<IndexArticleViewModel>((int)id);
            if (article == null)
            {
                return this.NotFound();
            }

            return this.View(article);
        }

        [HttpPost]
        [ActionName("HardDelete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this.articleService.HardDeleteById(id);

            return this.RedirectToAction(nameof(this.AllActive));
        }
    }
}

Web/ENews.Web/Areas/Administration/Controllers/UsersController.cs
namespace ENews.Web.Areas.Administration.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using ENews.Common;
    using ENews.Data;
    using ENews.Services;
    using ENews.Services.Data;
    using ENews.Web.ViewModels.Administration.Users;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class UsersController : BaseAdminController
    {
        private readonly IPagingService pagingService;
        private readonly IUsersService usersService;

        public UsersController(
            IPagingService pagingService,
            IUsersService usersService)
        {
            this.pagingService = pagingService;
            this.usersService = usersService;
        }

        public IActionResult Banned(string sortBy, string search, int page = 1)
        {
            this.SortBy(sortBy);
            this.Search(search);

            var skip = this.pagingService.CountSkip(page, GlobalConstants.AdministrationItemsPerPage);

            var result = this.usersService.GetAllBanned(sortBy, search, GlobalConstants.AdministrationItemsPerPage, skip);

            var usersCount = this.usersService.GetCountofBannedUsersByName(search);

            var model = new IndexUsersViewModel()
            {
                Users = result,
                PagesCount = this.pagingService.PagesCount(usersCount, GlobalConstants.AdministrationItemsPerPage),
            };
            model.CurrentPage = this.pagingService.PagesCount(page, model.PagesCount);

            return this.View(model);
        }

        public IActionResult Active(string sortBy, string search, int page = 1)
        {
            this.SortBy(sortBy);
            this.Search(search);

            var skip = this.pagingService.CountSkip(page, GlobalConstants.AdministrationItemsPerPage);

            var result = this.usersService.GetAll(sortBy, search, GlobalConstants.AdministrationItemsPerPage, skip);

            var usersCount = this.usersService.GetCountofActiveAccountsByUsername(search);

            var model = new IndexUsersViewModel()
            {
                Users = result,
                PagesCount = this.pagingService.PagesCount(usersCount, GlobalConstants.AdministrationItemsPerPage),
            };
            model.CurrentPage = this.pagingService.SetPage(page, model.PagesCount);

            return this.View(model);
        }

        public async Task<IActionResult> Ban(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            await this.usersService.DeleteById(id);

            return this.RedirectToAction(nameof(this.Active));
        }

        public async Task<IActionResult> Unban(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            await this.usersService.UndeleteById(id);

            return this.RedirectToAction(nameof(this.Banned));
        }

        public async Task<IActionResult> AddRoleReporter(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            await this.usersService.AddReporterRoleToUser(id);
            return this.RedirectToAction(nameof(this.Active));

        }

        public async Task<IActionResult> RemoveRoleReporter(string id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            await this.usersService.RemoveRepoertRoleFromUser(id);
            return this.RedirectToAction(nameof(this.Active));
        }

        public IActionResult GetReporters()
        {
            var res = this.usersService.GetAllReporters();
            var test = Newtonsoft.Json.JsonConvert.SerializeObject(res);
            return this.Json(res);
        }
    }
}

Web/ENews.Web/Controllers/ArticlesController.cs
namespace ENews.Web.Controllers
{
    using System.Threading.Tasks;

    using ENews.Services.Data;
    using ENews.Web.ViewModels.Articles;
    using Microsoft.AspNetCore.Mvc;

    public class ArticlesController : Controller
    {
        private readonly IArticlesService articleService;

        public ArticlesController(IArticlesService articleService)
        {
            this.articleService = articleService;
        }

        public async Task<IActionResult> Index(int id)
        {
            var model = await this.articleService.GetArticleById<ArticleViewModel>(id);
            if (model == null)
            {
                return this.NotFound();
            }

            model.SeenCount = await this.articleService.AddToSeenCount(model.Id);
            return this.View(model);
        }
    }
}

Web/ENews.Web/Controllers/CategoriesController.cs
namespace ENews.Web.Controllers
{
    using System.Threading.Tasks;

    using ENews.Common;
    using ENews.Data.Models.Enums;
    using ENews.Services;
    using ENews.Services.Data;
    using ENews.Web.ViewModels;
    using ENews.Web.ViewModels.Categories;
    using Microsoft.AspNetCore.Mvc;

    public class CategoriesController : Controller
    {
        private readonly IArticlesService articlesService;
        private readonly ICategoriesService categoriesService;
        private readonly IPagingService pagingService;

        public CategoriesController(
            IArticlesService articlesService,
            ICategoriesService categoriesService,
            IPagingService pagingService)
        {
            this.articlesService = articlesService;
            this.categoriesService = categoriesService;
            this.pagingService = pagingService;
        }

        public async Task<IActionResult> Index(string data, int page = 1)
        {
            var viewModel = await this.categoriesService.GetCategoryByName<MainCategoryArticlesViewModel>(data);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            viewModel.Route = GlobalConstants.CategoryRoute;
            viewModel.Data = data;

            var skip = this.pagingService.CountSkip(page, GlobalConstants.ArticlePerPage);

            viewModel.CategoryArticles = this.articlesService.GetAllByCategoryId<ArticlePreviewViewModel>(viewModel.Id, GlobalConstants.ArticlePerPage, skip);

            var articlesCount = this.articlesService.GetCountByCategoryId(viewModel.Id);

            viewModel.PagesCount = this.pagingService.PagesCount(articlesCount, GlobalConstants.ArticlePerPage);

            viewModel.CurrentPage = this.pagingService.SetPage(page, viewModel.PagesCount);

            return this.View(viewModel);
        }

        public IActionResult Local(int page = 1)
        {
            var viewModel = new LocalArticlesViewModel();

            viewModel.Route = GlobalConstants.LocalRoute;

            var skip = this.pagingService.CountSkip(page, GlobalConstants.ArticlePerPage);

            viewModel.CategoryArticles = this.articlesService.GetLatesLocalArticles<ArticlePreviewViewModel>(GlobalConstants.ArticlePerPage, skip);

            viewModel.PagesCount = this.pagingService.GetPagesCountByRegion(null);

            viewModel.CurrentPage = this.pagingService.SetPage(page, viewModel.PagesCount);

            return this.View(viewModel);
        }

        public IActionResult LocalByRegion(Region data, int page = 1)
        {
            if (data == 0)
            {
                return this.NotFound();
            }

            var viewModel = new RegionArticlesViewModel() { Data = data.ToString() };

            viewModel.Route = GlobalConstants.LocalByRegionRoute;

            var skip = this.pagingService.CountSkip(page, GlobalConstants.ArticlePerPage);

            viewModel.CategoryArticles = this.articlesService.GetLatestByRegion<ArticlePreviewViewModel>(data, GlobalConstants.ArticlePerPage, skip);

            viewModel.PagesCount = this.pagingService.GetPagesCountByRegion(data);

            viewModel.CurrentPage = this.pagingService.SetPage(page, viewModel.PagesCount);

            return this.View(viewModel);
        }
    }
}

Web/ENews.Web/Controllers/UsersController.cs
namespace ENews.Web.Controllers
{
    using System.Threading.Tasks;

    using ENews.Common;
    using ENews.Data.Models;
    using ENews.Services;
    using ENews.Services.Data;
    using ENews.Web.ViewModels;
    using ENews.Web.ViewModels.Articles;
    using ENews.Web.ViewModels.Users;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class UsersController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IArticlesService articlesService;
        private readonly IPagingService pagingService;
        private readonly UserManager<ApplicationUser> userManager;

        public UsersController(
            IUsersService usersService,
            IArticlesService articlesService,
            IPagingService pagingService,
            UserManager<ApplicationUser> userManager)
        {
            this.usersService = usersService;
            this.articlesService = articlesService;
            this.pagingService = pagingService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index(string username)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var model = await this.usersService.GetUserByUsername<UserProfileViewModel>(username);
            if (user != null)
            {
                model.MyProfile = user.Id == model.Id;
            }

            var result = this.articlesService.GetAllByAtuthorId<ArticleBaseViewModel>(model.Id, 4, 0);
            model.MyArticles = result;
            return this.View(model);
        }

        public async Task<IActionResult> Articles(string data, int page = 1)
        {
            var viewModel = await this.usersService.GetUserByUsername<UserArticlesViewModel>(data);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            viewModel.Route = GlobalConstants.UsernameRoute;
            viewModel.Data = data;

            var skip = this.pagingService.CountSkip(page, GlobalConstants.ArticlePerPage);

            viewModel.UserArticles = this.articlesService.GetAllByAtuthorId<ArticlePreviewViewModel>(viewModel.Id, GlobalConstants.ArticlePerPage, skip);

            var articlesCount = this.articlesService.GetCountByAuthorId(viewModel.Id);

            viewModel.PagesCount = this.pagingService.PagesCount(articlesCount, GlobalConstants.ArticlePerPage);

            viewModel.CurrentPage = this.pagingService.SetPage(page, viewModel.PagesCount);

            return this.View(viewModel);
        }
    }
}

Web/ENews.Web/ViewComponents/LatesArticlesViewComponent.cs
namespace ENews.Web.ViewComponents
{
    using ENews.Services.Data;
    using ENews.Web.ViewModels;
    using ENews.Web.ViewModels.Shared.Components.LatestArticles;
    using Microsoft.AspNetCore.Mvc;

    public class LatesArticlesViewComponent : ViewComponent
    {
        private readonly IArticlesService articleService;

        public LatesArticlesViewComponent(IArticlesService articleService)
        {
            this.articleService = articleService;
        }

        public IViewComponentResult Invoke(int count, int skip = 0)
        {
            var model = new LatestArticlesViewModel
            {
                Articles = this.articleService.GetLatesByCreatedOn<ArticlePreviewViewModel>(count, skip),
            };
            return this.View(model);
        }
    }
}

Web/ENews.Web/ViewComponents/LatestCommentsViewComponent.cs
namespace ENews.Web.ViewComponents
{
    using ENews.Services.Data;
    using ENews.Web.ViewModels.Comments;
    using ENews.Web.ViewModels.Shared.Components.LatestComments;
    using Microsoft.AspNetCore.Mvc;

    public class LatestCommentsViewComponent : ViewComponent
    {
        private readonly ICommentsService commentsService;

        public LatestCommentsViewComponent(ICommentsService commentsService)
        {
            this.commentsService = commentsService;
        }

        public IViewComponentResult Invoke()
        {
            var model = new LatestCommentsViewModel
            {
                Comments = this.commentsService.GetLatesByCreatedOn<CommentPreviewViewModel>(4),
            };

            return this.View(model);
        }
    }
}

Web/ENews.Web/ViewComponents/MostCommentedNewsViewComponent.cs
using ENews.Services.Data;
using ENews.Web.ViewModels;
using ENews.Web.ViewModels.Home;
using ENews.Web.ViewModels.Shared.Components.MostCommentedNews;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ENews.Web.ViewComponents
{
    public class MostCommentedNewsViewComponent : ViewComponent
    {
        private readonly IArticlesService articleService;

        public MostCommentedNewsViewComponent(IArticlesService articleService)
        {
            this.articleService = articleService;
        }

        public IViewComponentResult Invoke()
        {
            var model = new MostCommentedNewsViewModel
            {
                Articles = this.articleService.GetLatesMostCommented<ArticlePreviewViewModel>(5),
            };

            return this.View(model);
        }
    }
}

Web/ENews.Web/Views/Users/Articles.cshtml
@model ENews.Web.ViewModels.Users.UserArticlesViewModel

@{
    this.ViewData["Title"] = Model.Data;
}

<h1 class="text-center">Articles from @Model.Data</h1>
<br />
<!-- ##### Blog Area Start ##### -->
<div class="blog-area section-padding-0-80">
    <div class="row">
        <div class="col-12 col-lg-8">
            <div class="blog-posts-area">
                <!-- Single Featured Post -->
                @foreach (var article in Model.UserArticles)
                {
                    <div class="single-blog-post featured-post mb-30">
                        <div class="post-thumb">
                            <a asp-area="" asp-controller="Articles" asp-action="Index" asp-route-title="@article.Title.Replace(' ', '-')" asp-route-id="@article.Id"><img src="@article.PictureImageUrl" style='height: 100%; width: 100%; object-fit: contain' alt=""></a>
                        </div>
                        <div class="post-data">
                            <a asp-area="" asp-controller="Categories" asp-action="Index" asp-route-data="@article.CategoryTitle" class="post-catagory">@article.CategoryTitle</a>
                            <a asp-area="" asp-controller="Articles" asp-action="Index" asp-route-title="@article.Title.Replace(' ', '-')" asp-route-id="@article.Id" class="post-title">
                                <h6>@article.Title</h6>
                            </a>
                            <div class="post-meta">
                                <p class="post-author">
                                    By <a asp-controller="Users" asp-action="Index" asp-route-username="@article.AuthorUserName">
                                        @if (article.AuthorFirstName == null)
                                        {
                                            @article.AuthorUserName
                                        }
                                        else
                                        {
                                            @article.AuthorFullName
                                        }
                                    </a>
                                </p>
                                <p class="post-excerp">@article.ContetPreview</p>
                                <!-- Post Like & Post Comment -->
                                <div class="d-flex align-items-center">
                                    <p class="post-like"><i class="fa fa-eye text-muted fsize-3"></i> <span>@article.SeenCount</span></p>
                                    <p class="post-comment"><img src="~/img/core-img/chat.png" alt=""> <span>@article.CommentsCount</span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>

            <partial name="_ArticlesPaging" />
        </div>
        <div class="col-12 col-lg-4">
            <div class="blog-sidebar-area">

                <!-- Latest Posts Widget -->
                <div class="latest-posts-widget mb-50">
                    <vc:lates-articles count="6" , skip="0"></vc:lates-articles>
                </div>

                <!-- Popular News Widget -->
                <vc:most-commented-news count="4" skip="0"></vc:most-commented-news>

                <!-- Latest Comments Widget -->
                <vc:latest-comments></vc:latest-comments>
            </div>
        </div>
    </div>
</div>

Web/ENews.Web/Views/Users/Index.cshtml
@using ENews.Common;
@model ENews.Web.ViewModels.Users.UserProfileViewModel;
@using ENews.Data.Models;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> SignInManager;
@inject UserManager<ApplicationUser> UserManager;

@{
    this.ViewData["Title"] = Model.UserName;
    var str = Model.FirstName + " " + Model.LastName;
}

<!-- Profile widget -->
<body class="profile-background">
    <div class="bg-white shadow rounded overflow-hidden">
        <div class="px-4 pt-0 pb-4 cover">
            <div class="media align-items-end profile-head">
                <div class="profile mr-3">
                    <a href="#">
                        @if (string.IsNullOrWhiteSpace(Model.ProfilePictureImageUrl))
                        {
                            <img src="@GlobalConstants.ProfilePictureFill" alt="..." width="130" class="rounded mb-2 img-thumbnail">
                        }
                        else
                        {
                            <img src="@Model.ProfilePictureImageUrl" alt="..." width="130" class="rounded mb-2 img-thumbnail">
                        }
                    </a>
                    @if (Model.MyProfile)
                    {
                        <a asp-area="Identity" asp-controller="Account" asp-action="Manage" class="btn btn-outline-dark btn-sm btn-block">Edit profile</a>
                    }
                </div>
                <div class="media-body mb-5 text-white">
                    <h4 class="mt-0 mb-0 text-info">
                        @if (string.IsNullOrWhiteSpace(Model.FirstName))
                        {
                            @Model.UserName
                        }
                        else
                        {
                            @string.Concat(Model.FirstName, " ", Model.LastName)
                        }
                    </h4>
                    <p class="small mb-4 text-info"> <i class="fas fa-map-marker-alt mr-2"></i>New York</p>
                </div>
            </div>
        </div>
        <div class="bg-light p-4 d-flex justify-content-end text-center">
            <ul class="list-inline mb-0">
                <li class="list-inline-item">
                    <h5 class="font-weight-bold mb-0 d-block">215</h5><small class="text-muted"> <i class="fas fa-image mr-1"></i>Photos</small>
                </li>
                <li class="list-inline-item">
                    <h5 class="font-weight-bold mb-0 d-block">745</h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Followers</small>
                </li>
                <li class="list-inline-item">
                    <h5 class="font-weight-bold mb-0 d-block">340</h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Following</small>
                </li>
            </ul>
        </div>
        <div class="px-4 py-3">
            <h5 class="mb-0">About</h5>
            <div class="p-4 rounded shadow-sm bg-light">
                @if (string.IsNullOrWhiteSpace(@Model.Biography))
                {
                    <p class="font-italic mb-0">@GlobalConstants.BiographyFiller</p>
                }
                else
                {
                    <p class="font-italic mb-0">@Model.Biography</p>
                }
            </div>
        </div>
        <div class="py-4 px-4">
            @if (Model.MyArticles.Any())
            {
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="mb-0">Recent Articles</h5>
                    <a asp-area="" asp-controller="Users" asp-action="Articles" asp-route-data="@Model.UserName" class="btn btn-link text-muted">Show all</a>
                </div>

                <div class="row">
                    @foreach (var article in Model.MyArticles)
                    {
                        <div class="card col-lg-6 mb-2">
                            <a asp-area="" asp-controller="Articles" asp-action="Index" asp-route-title="@article.Title.Replace(' ', '-')" asp-route-id="@article.Id">
                                <img class="card-img-top" style="height:300px" src="@article.PictureImageUrl"  alt="Card image cap">
                                <div class="card-body">@article.Title</div>
                            </a>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</body>